services:
    dev:
        build:
            context: .
            target: development
        image: eruizmoreno/unknown-gravity:tbtc-relayer-dev
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "4000:3333"
        environment:
            APP_NAME: "tBTC Relayer"
            APP_POST: 3333
            APP_URL: "http://localhost:3000"
            JSON_PATH: "./data/"
            CLEAN_QUEUED_TIME: 48
            CLEAN_FINALIZED_TIME: 12
            PRIVATE_KEY: "4bd226a432c44333bc0e1a0830f7c65a18eaaa862c26fd5c1e603f59511adca3"
            EthereumRPC: "https://go.getblock.io/a9fb8ec5f3714a148185fb0d2d139d61"
            ArbitrumRPC: "https://go.getblock.io/1244cf394ef143ae9b4eac44899ec6f4"
            L1BitcoinDepositor: "0xD9B523fb879C63b00ef14e48C98f4e3398d3BA2D"
            L2BitcoinDepositor: "0xB2fEC598a9374078Bb639f3d70555fc4389b7a78"
            TBTCVaultSepolia: "0xB5679dE944A79732A75CE556191DF11F489448d5"
        command: npm run start:dev
